# Generated by Django 4.2.1 on 2023-06-05 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='single_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField()),
                ('time', models.IntegerField()),
                ('waiting_time', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bread_number', models.IntegerField()),
                ('random_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField()),
                ('time', models.IntegerField()),
                ('waiting_time', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bread_number', models.IntegerField()),
                ('random_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
