# Generated by Django 4.2.1 on 2023-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode_image',
            field=models.ImageField(default=2, upload_to='qrcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='random_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
