# Generated by Django 4.2.1 on 2023-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_barcode_image_alter_order_random_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barcode_image',
        ),
        migrations.AlterField(
            model_name='single_order',
            name='random_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
